services:
  db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - ./database/movies_with_actormapping.sql:/docker-entrypoint-initdb.d/moviedbdata.sql

  backend:
    image: movies-backend
    container_name: movies_backend
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres

  frontend:
    profiles: ["all"]
    build: ./frontend
    container_name: movies_frontend
    depends_on:
      - backend
    ports:
      - 3000:3000